// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFskwVUFba55Mu5GRpZ9y1VRLoc1hpcCw',
    appId: '1:656522439903:web:82a3f1dd6d2122048b4d6a',
    messagingSenderId: '656522439903',
    projectId: 'study-planner-e1801',
    authDomain: 'study-planner-e1801.firebaseapp.com',
    storageBucket: 'study-planner-e1801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrZrTwAueVminN3Bhxg4rqa9jjh7wLdY',
    appId: '1:656522439903:android:628cc7733db0e9db8b4d6a',
    messagingSenderId: '656522439903',
    projectId: 'study-planner-e1801',
    storageBucket: 'study-planner-e1801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWbkNr9J04zgJP8H-XwNpKPP_dn2tIOo',
    appId: '1:656522439903:ios:0b42c9d9eb468f248b4d6a',
    messagingSenderId: '656522439903',
    projectId: 'study-planner-e1801',
    storageBucket: 'study-planner-e1801.appspot.com',
    iosBundleId: 'com.example.studyPlannerFluter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClWbkNr9J04zgJP8H-XwNpKPP_dn2tIOo',
    appId: '1:656522439903:ios:0b42c9d9eb468f248b4d6a',
    messagingSenderId: '656522439903',
    projectId: 'study-planner-e1801',
    storageBucket: 'study-planner-e1801.appspot.com',
    iosBundleId: 'com.example.studyPlannerFluter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFskwVUFba55Mu5GRpZ9y1VRLoc1hpcCw',
    appId: '1:656522439903:web:7f134a71d44340ef8b4d6a',
    messagingSenderId: '656522439903',
    projectId: 'study-planner-e1801',
    authDomain: 'study-planner-e1801.firebaseapp.com',
    storageBucket: 'study-planner-e1801.appspot.com',
  );
}
